### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: Volba nastavení účtu
metadata:
  title: Volba nastavení účtu
  description: Volba nastavení účtu
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: aad1cf9d3b07fe699cbb827cc0a4363712786394
  ms.sourcegitcommit: 077f8eb202a6505eeecfd1a2d6314656ed4d7d70
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/13/2018
  ms.locfileid: "53347678"
durationInMinutes: 5
content: '[!include[](includes/3-choose-your-account-settings.md)]'
