### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: Cvičení – konfigurace aplikací na posílání nebo příjem zpráv prostřednictvím centra událostí
metadata:
  title: Cvičení – konfigurace aplikací na posílání nebo příjem zpráv prostřednictvím centra událostí
  description: Nakonfigurujete aplikace k odesílání nebo příjmu zpráv prostřednictvím centra událostí.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: dd61d603b68826000437084a31205bd48454aa7e
  ms.sourcegitcommit: ad6eb8a6c90f3633f4302f972532441a6fccc989
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/06/2018
  ms.locfileid: "53005862"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
