### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Cvičení – Povolení a konfigurace mezipaměti disku virtuálního počítače Azure přes Azure Portal
metadata:
  title: Cvičení – Povolení a konfigurace mezipaměti disku virtuálního počítače Azure přes Azure Portal
  description: Cvičení – Povolení a konfigurace mezipaměti disku virtuálního počítače Azure přes Azure Portal
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 5b5f187ea6163345c8eb562d50be7e1f9e9a1fd9
  ms.sourcegitcommit: d60baa2d00011ced74fd5734a9e5efdff04aca5e
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/21/2018
  ms.locfileid: "53732783"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-exercise-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)]'
