### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.6-exercise-manage-cache-settings-with-powershell
title: Cvičení – správa nastavení mezipaměti s využitím PowerShellu
metadata:
  title: Cvičení – správa nastavení mezipaměti s využitím PowerShellu
  description: Cvičení – správa nastavení mezipaměti s využitím PowerShellu
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: bcc461dbc74093fd6ef21384aa0715f829889fee
  ms.sourcegitcommit: d60baa2d00011ced74fd5734a9e5efdff04aca5e
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/21/2018
  ms.locfileid: "53732783"
interactive: powershell
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/6-exercise-manage-cache-settings-with-powershell.md)]'
