### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.8-exercise-add-azure-storage-configuration-to-your-app
title: Přidání konfigurace služby Azure Storage do aplikace
metadata:
  title: Přidání konfigurace služby Azure Storage do aplikace
  description: Přidání konfigurace služby Azure Storage do aplikace
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: e15c48348cbfbd7a1f1b4188a49bc640dd6fc0fb
  ms.sourcegitcommit: ad6eb8a6c90f3633f4302f972532441a6fccc989
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/06/2018
  ms.locfileid: "53006188"
interactive: bash-editor
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/8-exercise-add-azure-storage-configuration-to-your-app.md)]'
