### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Určení kritických bodů z hlediska výkonu aplikace
metadata:
  title: Určení kritických bodů z hlediska výkonu aplikace
  description: V této lekci se budeme zabývat určováním kritických bodů z hlediska výkonu aplikace
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 428286554728928f40d45376b09997029af479f9
  ms.sourcegitcommit: d60baa2d00011ced74fd5734a9e5efdff04aca5e
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/21/2018
  ms.locfileid: "53732725"
durationInMinutes: 9
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: Kontrola znalostí
  questions:
  - content: Která z následujících možností nejlépe popisuje službu Application Insights?
    choices:
    - content: Jedno zobrazení pro všechny vaše potřeby monitorování v Azure
      isCorrect: false
      incorrectExplanation: I když služba Application Insights poskytuje širokou škálu údajů o výkonu aplikace, nejedná se o komplexní řešení monitorování Azure.
    - content: Implementace modelu monitorování stavu pomocí koncových bodů
      isCorrect: false
      incorrectExplanation: Model monitorování stavu podle koncových bodů se zaměřuje na monitorování celkového stavu koncových bodů exponovaných u vaší aplikace.
    - content: Pracovní prostor umožňující shromažďování protokolů z celé infrastruktury a aplikací
      isCorrect: false
      incorrectExplanation: Log Analytics je pracovní prostor umožňující shromažďování protokolů napříč infrastrukturou a aplikacemi.
    - content: Služba monitorující dostupnost, výkon a využití webových aplikací
      isCorrect: true
      correctExplanation: Application Insights je služba monitorující dostupnost, výkon a využití webových aplikací.
  - content: 'Ano nebo ne: Log Analytics sleduje vlastní protokoly a metriky.'
    choices:
    - content: Ano
      isCorrect: true
      correctExplanation: Pro vlastní protokoly a metriky můžete použít rozhraní API kolekce dat HTTP a zapisovat data do Log Analytics z jakéhokoli klienta REST API, nebo použít Azure Logic App a zapisovat data z vlastního pracovního postupu.
    - content: Ne
      isCorrect: false
      incorrectExplanation: Pro vlastní protokoly a metriky můžete použít rozhraní API kolekce dat HTTP a zapisovat data do Log Analytics z jakéhokoli klienta REST API, nebo použít Azure Logic App a zapisovat data z vlastního pracovního postupu.
