### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: Ochrana sítě
metadata:
  title: Ochrana sítě
  description: V této lekci probereme, jak můžete zabezpečit síťovou infrastrukturu.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: f79346613fbc2ffd70b4da7f12dd9a2a83953aec
  ms.sourcegitcommit: 1994bbbea31b0ad05ebb6c1b26c63b4f2d2ecf7c
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/05/2018
  ms.locfileid: "52928827"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
