### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Konfigurace služby Azure Cache for Redis
metadata:
  title: Konfigurace služby Azure Cache for Redis
  description: Konfigurace služby Azure Cache for Redis
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: a18fe517364a93549086fe2eb7840db6b979981f
  ms.sourcegitcommit: d60baa2d00011ced74fd5734a9e5efdff04aca5e
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/21/2018
  ms.locfileid: "53732427"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
