### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: Konfigurace a inicializace knihovny klienta
metadata:
  title: Konfigurace a inicializace knihovny klienta
  description: Konfigurace a inicializace knihovny klienta
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: f79987228c4ee6c48218194c24d8ccf949445d9d
  ms.sourcegitcommit: ad6eb8a6c90f3633f4302f972532441a6fccc989
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/06/2018
  ms.locfileid: "53006151"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
