### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Vytvoření aplikace Azure IoT Central
metadata:
  title: Vytvoření aplikace Azure IoT Central
  description: Vytvoření aplikace Azure IoT Central
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 1c131e1bb1b76f0f0c6690a64c907a14180597bc
  ms.sourcegitcommit: 1994bbbea31b0ad05ebb6c1b26c63b4f2d2ecf7c
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/05/2018
  ms.locfileid: "52926179"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
