### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: Připojení simulovaného kávovaru k aplikaci
metadata:
  title: Připojení simulovaného kávovaru k aplikaci
  description: Připojení simulovaného kávovaru k aplikaci
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 3973e10aada6ead4b026e6fdfe0986d7764649ba
  ms.sourcegitcommit: 1994bbbea31b0ad05ebb6c1b26c63b4f2d2ecf7c
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/05/2018
  ms.locfileid: "52926179"
interactive: bash
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
