### YamlMime:ModuleUnit
uid: learn.secure-your-azure-sql-database.4-data-security
metadata:
  title: Zabezpečení dat při přenosu, v klidovém stavu a při zobrazení
  description: Zabezpečení dat
  ms.date: 11/09/2018
  author: jboeshart
  ms.author: jaboes
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 99f7a43cd60e9ddab1e1e5e7c9fddc62717bfb5d
  ms.sourcegitcommit: 1994bbbea31b0ad05ebb6c1b26c63b4f2d2ecf7c
  ms.translationtype: HT
  ms.contentlocale: cs-CZ
  ms.lasthandoff: 12/05/2018
  ms.locfileid: "52932079"
interactive: bash
azureSandbox: true
title: Zabezpečení dat při přenosu, v klidovém stavu a při zobrazení
durationInMinutes: 8
content: '[!include[](includes/4-data-security.md)]'
